name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master

jobs:
  call-workflow:
    uses: tikenek/terraform-adding-users/.github/workflows/terraform-template-apply.yml@v1
 
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    




