name: test

on:
  workflow_dispatch:
 
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  call-workflow:
    uses: tikenek/terraform-adding-users/.github/workflows/terraform-template-apply.yml@v1
  sync:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
 

